name        : gtkhotkey
version     : 0.2.1
release     : 3
source      :
    - http://launchpad.net/gtkhotkey/0.2/0.2.1/+download/gtkhotkey-0.2.1.tar.gz : fe1cf0d93026d791e856170356f56fbdff9095fe637c4a74104144c1e5111d67
homepage    : https://launchpad.net/gtkhotkey
license     : GPL-2.0
component   : desktop.library
summary     : Platform independent hotkey handling for Gtk+ applications
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - intltool
description : |
    Platform independent hotkey handling for Gtk+ applications
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-import-individual-glib-headers.patch
    %patch -p1 < $pkgfiles/0002-Use-correct-location-for-documentation-files.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
